name: Build and Create Draft Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build_and_draft_release:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: ./.github/actions/install-poetry-and-dependencies
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build
        run: |
          poetry self add poetry-git-version-plugin
          poetry build
      - uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref }}
          draft: true
          files: dist/*
