name: Python CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # uv-dynamic-versioning がタグ/履歴を必要とするため
      - name: Set up uv and install dependencies
        uses: ./.github/actions/install-uv-and-dependencies
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check dependencies for vulnerabilities
        run: |
          uv export --format requirements.txt --no-emit-project --no-dev -o requirements.txt
          uvx pip-audit -r requirements.txt
      - name: Check lockfile is up to date
        run: uv lock --check
      - name: Lint
        if: github.event_name != 'push'
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --relative origin/${{ github.base_ref }}... --name-only | xargs uv run pre-commit run --files
      - name: Test
        run: uv run poe test
